#!/bin/sh
eval `dbus export shadowsocks`
source /koolshare/configs/ss.sh
black=$(echo $ss_black_lan | sed "s/,/ /g")
white=$(echo $ss_white_lan | sed "s/,/ /g")
lan_ipaddr=$(nvram get lan_ipaddr)
server_ip=`resolvip $ss_server`
ip1=$(nvram get wan0_ipaddr | cut -d"." -f1)
ip2=$(nvram get wan0_ipaddr | cut -d"." -f2)

# Different routers got different iptables syntax
case $(uname -m) in
  armv7l)
    MATCH_SET='--match-set'
    ;;
  mips)
    MATCH_SET='--set'
    ;;
esac

if [ -z "$shadowsocks_server_ip" ];then
        if [ ! -z "$server_ip" ];then
                export shadowsocks_server_ip="$server_ip"
                ss_server="$server_ip"
                dbus save shadowsocks
        fi
else
        if [ "$shadowsocks_server_ip"x = "$server_ip"x ];then
                ss_server="$shadowsocks_server_ip"
        elif [ "$shadowsocks_server_ip"x != "$server_ip"x ] && [ ! -z "$server_ip" ];then
                ss_server="$server_ip"
                export shadowsocks_server_ip="$server_ip"
                dbus save shadowsocks
        else
                ss_server="$shadowsocks_server_ip"
        fi
fi

# flush and destory ipset if any
iptables -t nat -F SHADOWSOCKS > /dev/null 2>&1
iptables -t nat -D PREROUTING -p tcp -j SHADOWSOCKS >/dev/null 2>&1
iptables -t nat -X SHADOWSOCKS > /dev/null 2>&1
iptables -t nat -D OUTPUT -p tcp -m set --match-set router dst -j REDIRECT --to-ports 3333 >/dev/null 2>&1
ipset -F router >/dev/null 2>&1
ipset -F gfwlist >/dev/null 2>&1
ipset -X router >/dev/null 2>&1
ipset -X gfwlist >/dev/null 2>&1

# Create new set
ipset -N router iphash
ipset -N gfwlist iphash

# Create new chain
iptables -t nat -N SHADOWSOCKS

# Ignore LANs and any other addresses you'd like to bypass the proxy
iptables -t nat -A SHADOWSOCKS -d $ss_server -j RETURN
iptables -t nat -A SHADOWSOCKS -d 0.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 169.254.0.0/16 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 172.16.0.0/12 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 224.0.0.0/4 -j RETURN
iptables -t nat -A SHADOWSOCKS -d 240.0.0.0/4 -j RETURN
iptables -t nat -A SHADOWSOCKS -d $ip1.$ip2.0.0/16 -j RETURN

# iptables -t nat -A SHADOWSOCKS -p tcp -m set --match-set router dst -j REDIRECT --to-ports 3333


# lan control
if [ "$ss_lan_control" == "1" ];then
	if [ ! -z $ss_black_lan ];then
		for balck_ip in $black
		do
			iptables -t nat -A SHADOWSOCKS -p tcp -s $balck_ip -j RETURN
		done
		iptables -t nat -A SHADOWSOCKS -p tcp -m set $MATCH_SET gfwlist dst -j REDIRECT --to-ports 3333
	else
	iptables -t nat -A SHADOWSOCKS -p tcp -m set $MATCH_SET gfwlist dst -j REDIRECT --to-ports 3333
	fi
elif [ "$ss_lan_control" == "2" ];then
	if [ ! -z $ss_white_lan ];then
		for white_ip in $white
		do
			iptables -t nat -A SHADOWSOCKS -p tcp -s $white_ip -m set $MATCH_SET gfwlist dst -j REDIRECT --to-ports 3333
		done
	else
		iptables -t nat -A SHADOWSOCKS -p tcp -m set $MATCH_SETgfwlist dst -j REDIRECT --to-ports 3333
	fi
else
	iptables -t nat -A SHADOWSOCKS -p tcp -m set $MATCH_SET gfwlist dst -j REDIRECT --to-ports 3333
fi

iptables -t nat -A PREROUTING -p tcp -j SHADOWSOCKS

# Apply the rules for router self
iptables -t nat -A OUTPUT -p tcp -m set $MATCH_SET router dst -j REDIRECT --to-ports 3333

	if [ "$ss_chromecast" == "1" ]; then
		echo $(date): enable lan dns take over, i.e chromecast...
		iptables -t nat -A PREROUTING -s $lan_ipaddr/24 -p udp --dport 53 -j DNAT --to $lan_ipaddr >/dev/null 2>&1
		echo $(date): done
		echo $(date):
	else
		echo $(date): disable lan dns take over..
		iptables -t nat -D PREROUTING -s $lan_ipaddr/24 -p udp --dport 53 -j DNAT --to $lan_ipaddr >/dev/null 2>&1
		echo $(date): done
		echo $(date):
	fi


