#!/bin/sh
eval `dbus export shadowsocks`
eval `dbus export ss`
source /koolshare/scripts/base.sh


kill `ps | grep ss-local | grep -v "grep" | grep -v "23456"|awk '{print $1}'`  >/dev/null 2>&1
# Start ss-local
if [ "$ss_local_enable" == "1" ]; then
	echo $(date): enable ss_local...
	ss-local -b 0.0.0.0 -s "$ss_local_server" -p "$ss_local_port" -l "$ss_local_proxyport" -k "$ss_local_password" -m "$ss_local_method" -u -f /var/run/ss_local.pid
	echo $(date): done
	echo $(date):
fi


